# Generated by Django 5.2.6 on 2025-11-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('manager', 'Менеджер')], default='owner', max_length=20),
        ),
    ]
