# Generated by Django 5.2.6 on 2025-11-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='recipient',
            new_name='recipients',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='finish_sending',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
