# Generated by Django 5.2.6 on 2025-11-16 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0005_message_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('fail', 'Неудачно')])),
                ('server_response', models.TextField(blank=True, null=True)),
                ('attemted_at', models.DateTimeField(auto_now_add=True)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='рассылка', to='mailing_app.mailing')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_app.recipient')),
            ],
            options={
                'verbose_name': 'попытка',
                'verbose_name_plural': 'попытки',
            },
        ),
    ]
